### ISSUE TITLE
Update GitHub Action (on 2.0.15+1 vs. 2.0.20) to get fixed versions

### ISSUE THREAD

**Issue by nkuehn** [filiph/linkcheck#93]
Hi, 
I'm trying to call the GitHub action with multiple arguments, but if I get the changelog right that only works from version `2.0.20` onwards.  But the latest action I can use from the marketplace is the one that is in the docs (`2.0.15+1`)

Using:
```
- name: Check links
  uses: filiph/linkcheck@v2.0.15+1
  with:
    arguments: --external --show-redirects --skip-file my-skip-list-file https://example.com
```

fails because the arguments are passed as one %-encoded argument. Maybe it's just a documentation problem how to pass multiple arguments to the GitHub action and how the versions relate. 

I'm helping myself by directly addresssing the container to be able to work with the latest version but it feels hacky because undocumented
```
- name: Check links
  uses: docker://tennox/linkcheck:2.0.20
  with:
    args: --external --show-redirects --skip-file my-skip-list-file https://example.com
```

Given the simplicity of this solution it could be documented, too if there's some issue or blocker to automating the github action release on new releases.
